#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          grdf_daemon
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: grdf_daemon...
### END INIT INFO

# Must be a valid filename
NAME=grdf_launcher.sh
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/home/grdf/projetGRDF/grdf_daemon/grdf_launcher.sh

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "."
	;;
  force-stop)
    d_stop
    killall -q $daemon_NAME || true
    sleep 2
    killall -q -9 $daemon_NAME || true
    !;
 
  status)
    status_of_proc "$daemon_NAME" "$DAEMON" "system-wide $daemon_NAME" && exit 0 || exit $?
    ;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0


